apiVersion: apps/v1
kind: Deployment
metadata:
   name: my-app
spec:
   replicas: 1
   selector:
    matchLabels:
      app: my-app
   template:
     metadata:
       name: my-app
       labels:
         app: my-app
     spec:
       containers:
         - name: my-app
           image: marssag/my-app:2.0.4
           ports:
             - containerPort: 8080
