apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  type: NodePort
  ports:
  - port: 5005
    targetPort: 5005
    nodePort: 32005
  selector:
    app: oms-api-app
